name: clipboard
description: "CopyCat Clipboard: One Clipboard, Limitless Productivity"
publish_to: "none"
version: 1.2.0+71

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  injectable: ^2.4.2
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  path: ^1.9.0
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  go_router: ^15.1.3
  dartz: ^0.10.1
  form_validator: ^2.1.1
  window_manager: ^0.4.2
  timeago: ^3.7.0
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev
  uuid: ^4.4.2
  rxdart: ^0.28.0
  internet_connection_checker_plus: ^2.3.0
  url_launcher: ^6.3.0
  googleapis: ^13.1.0
  file_picker: ^10.3.2
  http: ^1.2.2
  blurhash_dart: ^1.2.1
  mime: ^1.0.5
  image: ^4.2.0
  intl: ^0.20.2
  app_links: ^6.3.3
  device_preview: ^1.2.0
  async: ^2.11.0
  win32_registry: ^1.1.3
  share_handler: ^0.0.21
  universal_io: ^2.2.2
  duration: ^4.0.3
  open_filex: ^4.4.0
  hotkey_manager: ^0.2.3
  google_mobile_ads: ^6.0.0
  focus_window:
    path: ./packages/focus_window
  package_info_plus: ^8.0.0
  tray_manager: ^0.5.0
  flutter_platform_alert: ^0.8.0
  device_preview_screenshot: ^1.0.0
  encrypt: ^5.0.3
  upgrader: ^11.4.0
  retry: ^3.1.2
  launch_at_startup: ^0.3.1
  copycat_pro:
    path: packages/copycat_pro
  copycat_base:
    path: packages/copycat_base
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.10+1
  screen_retriever: ^0.2.0
  flutter_svg_provider:
    git:
      url: https://github.com/raj457036/flutter_svg_provider.git
  android_background_clipboard:
    path: packages/android_background_clipboard
  sentry_flutter: ^9.6.0
  animate_do: ^3.3.4
  # installed_apps:
  #   git:
  #     url: https://github.com/raj457036/installed_apps.git
  installed_apps:
    path: packages/installed_apps
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video:
  emoji_picker_flutter:
    git:
      url: https://github.com/raj457036/emoji_picker_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev
  freezed: 2.5.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.3
  sentry_dart_plugin: ^2.0.0

dependency_overrides:
  intl: ^0.20.2
  analyzer: ^6.4.1
  screen_retriever: ^0.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: RobotoFlex
      fonts:
        - asset: fonts/RobotoFlex-VariableFont.ttf

flutter_launcher_icons:
  image_path: "./resources/icon.png"
  android: true
  min_sdk_android: 24

  ios: true
  remove_alpha_ios: true

  windows:
    generate: true
    icon_size: 256
    image_path: "./resources/windows-icon.png"

  macos:
    generate: true
    image_path: "./resources/macos-icon.png"

sentry:
  upload_debug_symbols: true
